import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const userId = process.env.USER_ID ? process.env.USER_ID : false;
let user = {
  primaryColor: ""
};
if (userId) { 
  const data = await fetch(`http://localhost:1337/api/users/${userId}`)
  user = await data.json() 
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{backgroundColor: userId ? user.primaryColor : ""}}
      >
        {children}
      </body>
    </html>
  );
}
